"""initial

Revision ID: 5e3138664249
Revises: 
Create Date: 2026-04-26 16:46:21.073532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3138664249'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_style',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('interviewer_style_tags', sa.JSON(), nullable=False),
    sa.Column('preferred_question_types', sa.JSON(), nullable=False),
    sa.Column('sample_questions', sa.JSON(), nullable=False),
    sa.Column('prompt_context_text', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_style_id', sa.String(length=36), nullable=True),
    sa.Column('role_title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('question_count_target', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resume_context', sa.Text(), nullable=True),
    sa.Column('bidi_tokens_total', sa.Integer(), nullable=False),
    sa.Column('bidi_cost_usd', sa.Float(), nullable=False),
    sa.Column('bidi_started_at', sa.DateTime(), nullable=True),
    sa.Column('bidi_ended_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_style_id'], ['company_style.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('content_score', sa.Integer(), nullable=False),
    sa.Column('expression_score', sa.Integer(), nullable=False),
    sa.Column('voice_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_result', sa.String(length=20), nullable=False),
    sa.Column('improvement_suggestion', sa.Text(), nullable=False),
    sa.Column('ideal_answer', sa.Text(), nullable=True),
    sa.Column('voice_features', sa.JSON(), nullable=False),
    sa.Column('rubric_version', sa.String(length=20), nullable=False),
    sa.Column('raw_prompt', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('evaluation_cost_usd', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_audio_s3_key', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('user_audio_s3_key', sa.String(length=500), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('evaluation')
    op.drop_table('interview')
    op.drop_table('company_style')
    # ### end Alembic commands ###
