"""add_rubric_type_dimension_scores

Revision ID: 8b503bce660f
Revises: 5e3138664249
Create Date: 2026-05-11 18:54:05.905764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b503bce660f'
down_revision: Union[str, Sequence[str], None] = '5e3138664249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_style', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_type', sa.String(length=20), nullable=False, server_default='faang'))

    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimension_scores', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_column('dimension_scores')

    with op.batch_alter_table('company_style', schema=None) as batch_op:
        batch_op.drop_column('rubric_type')

    # ### end Alembic commands ###
